config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users

  root 'dashboard#index'

  resources :profiles

  resources :posts do
    post :publish
    get  :display
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :posts


  accepts_nested_attributes_for :profile

  after_create :create_default_profile

  private
  def create_default_profile
    self.create_profile(email: self.email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @posts = Post.select("id, published, title").where(user_id: current_user.id, published: false).order(updated_at: :desc)
    #@posts = Post.all

    #u = User.first( :joins => :cities, :select => "users.*, cities.name AS city_name")

    #@posts = Post(:joins => :users, :select => "posts.*,users.email").where(user_id: current_user.id).order(updated_at: :desc)

    @published = Post.joins(:user).where(published: true).select("posts.*,users.email").order(updated_at: :desc)

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(updated_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def publish
    @post = Post.find(params[:post_id])
    @post.published = true
    @post.save
    redirect_to "/"
  end

  def display
    @published = Post.find(params[:post_id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :published)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new(params[:profile])

    puts "!@!@!@@!@"
    puts @profile.save
    redirect_to @profile
  end

  def create
    @profile = Profile.new(params[:profile])
    puts "!@!@!@@!@"

    puts @profile.save
    redirect_to @profile
  end

  def show
  #  @profile = Profile.where(user_id: params[:id]).first
    @profile = Profile.find_by(user_id: params[:id])
    
  end

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard
%p Find me in app/views/dashboard/index.html.erb
#drafts.drafts
  %h2 Listing posts
  %table
    %thead
      %tr
        %th Title
        %th Published
        %th
        %th
        %th
    %tbody
      - @posts.each do |post|
        %tr
          %td
            = link_to post.title, post
          %td
            = link_to 'Show', post
          %td
            = link_to 'Edit', edit_post_path(post)
          %td
            = link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }
  %br/
= link_to 'New Post', new_post_path

#published.published
  %h2 Published Posts
  %table
    %thead
      %tr
        %th Title
        %th Email
        %th Published
        %th
        %th
    %tbody
      - @published.each do |post|
        %tr
          %td
            = link_to post.title, post
          %td
            = post.email
          %td
            = post.published
          %td
            = link_to 'Show', post_display_path(post)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<div class="header" id="header">
  <li>
   <%= link_to('Home', dashboard_index_path, :method => :get) %>
  </li>
  <li>
   <%= link_to('Profile', profile_path(current_user), :method => :get) %>
  </li>
  <li>
   <%= link_to('Log out', destroy_user_session_path, :method => :delete) %>
  </li>
  <form action= "/posts/new" >
    <input type="submit" value="Create Post">
  </form>
  <div class="field" name="user_name" value = current_user.email></div>
</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if user_signed_in?
      #header.header
        %li
          = link_to('Log out', destroy_user_session_path, :method => :delete)
        %li
          = link_to('Profile', profile_path(current_user), :method => :get)
        %p User name2
      = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/posts/display.html.haml
%p
  %b Title:
  = @published.title

%p
  %b Content:
  = @published.content

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'
= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Published
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.content
        %td= post.published
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'cancel', posts_path

app/views/posts/show.html.haml
%p#notice
  = notice
%p
  %b Title:
  = @post.title

.Title
  %p
    %b Title:
    = @post.title

#Title.field
  %p
    %b Title:
    = @post.title
%p
  %b Content:
  = @post.content
%p
  %b Published:
  = @post.published
= link_to 'Edit', edit_post_path(@post)
= link_to 'Publish', post_publish_path(@post), :method => "post"

\\|
\#{link_to 'Back', posts_path}

app/views/posts0/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/posts0/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts0/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Published
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.content
        %td= post.published
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts0/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts0/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Content:
  = @post.content
%p
  %b Published:
  = @post.published

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/profiles/index.html.haml
%h1 User Profile
%p Find me in app/views/profiles/index.html.erb
= form_for :profile do |f|
  %p
    = f.email :title
  %p
    = f.first_name :text
  %p
    = f.last_name :text

app/views/profiles/new.html.haml
%h1 User Profile
%p Find me in app/views/profiles/index.html.erb
%ul{:style => "list-style-type:disc"}
  %li Title | Content

app/views/profiles/show.html.haml
%h1 User Profile
%p Find me in app/views/profiles/show.html.erb

= form_for :profile do |f|
  %p
    = f.label :email
    %br
      = f.text_field :email
  %p
    = f.label :first_name
    %br
      = f.text_field :first_name
  %p
    = f.label :last_name
    %br
      = f.text_field :last_name
  %p
    = f.submit